# Generated by Django 2.0.7 on 2018-08-07 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0004_auto_20180807_0903'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование задачи')),
                ('datetime_of_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('date_todo', models.DateField(verbose_name='Дата выполнения')),
                ('time_todo', models.TimeField(verbose_name='Время выполнения')),
                ('status', models.CharField(max_length=20, verbose_name='Статус')),
                ('priority', models.CharField(max_length=20, verbose_name='Приоритет')),
                ('text', models.TextField(verbose_name='Описание задачи')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='creator', to='user.Employee', verbose_name='Создатель')),
                ('executor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='executor', to='user.Employee', verbose_name='Создатель')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
            },
        ),
    ]
