# Generated by Django 2.0.7 on 2018-08-07 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20180807_0903'),
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='task',
            name='executor',
        ),
        migrations.RemoveField(
            model_name='task',
            name='text',
        ),
        migrations.AddField(
            model_name='task',
            name='task_creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='task_creator', to='user.Employee', verbose_name='Создатель'),
        ),
        migrations.AddField(
            model_name='task',
            name='task_description',
            field=models.TextField(blank=True, verbose_name='Описание задачи'),
        ),
        migrations.AddField(
            model_name='task',
            name='task_executor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='task_executor', to='user.Employee', verbose_name='Создатель'),
        ),
    ]
