# Generated by Django 2.0.7 on 2018-08-07 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20180801_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactperson',
            name='dialing_code',
            field=models.CharField(max_length=10, verbose_name='Телефонный код города'),
        ),
    ]
