# Generated by Django 2.0.7 on 2018-08-07 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20180807_0903'),
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='client',
            name='responsible_manager',
        ),
        migrations.AddField(
            model_name='client',
            name='client_creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='client_creator', to='user.Employee', verbose_name='Создатель'),
        ),
        migrations.AddField(
            model_name='client',
            name='client_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='client_manager', to='user.Employee', verbose_name='Ответственный менеджер'),
        ),
    ]
