# Generated by Django 2.0.7 on 2018-07-29 13:22

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField()),
                ('phone_number', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message="Номер должен быть в формате '9633609225'", regex='^\\+?1?\\d{10}$')])),
                ('email', models.EmailField(max_length=254)),
                ('login_skype', models.CharField(max_length=50)),
                ('other_contacts', models.CharField(max_length=200)),
                ('confirmed_email', models.BooleanField()),
                ('blocked_account', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
        migrations.CreateModel(
            name='EmployeePosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Должность сотрудника',
                'verbose_name_plural': 'Должности сотрудников',
            },
        ),
        migrations.CreateModel(
            name='GroupEmployee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('description', models.TextField()),
                ('created_date', models.DateField()),
                ('creator', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='employee.Employee')),
                ('employees', models.ManyToManyField(related_name='employee', to='employee.Employee')),
            ],
        ),
    ]
